name: CI/CD with github actions & docker

on:
  push:
    branches: [ "ci-cd/#38-pipeline-implementation" ]

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          "com.bkmarriott.auth",
          "com.bkmarriott.charge",
          "com.bkmarriott.coupon",
          "com.bkmarriott.eureka",
          "com.bkmarriott.gateway",
          "com.bkmarriott.hotel",
          "com.bkmarriott.promotion",
          "com.bkmarriott.reservation"
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Inject application.yml
        run: |
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ${{ matrix.service }}/src/main/resources/application.yml
        env:
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}

      - name: Build with Gradle
        run: ./gradlew :${{ matrix.service }}:clean :${{ matrix.service }}:build -x test --no-daemon

      - name: Build Docker Image
        run: |
          cd ${{ matrix.service }}
          docker build -t my-app:${{ matrix.service }} .

      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push my-app:${{ matrix.service }}