server:
  port: 19091
spring:
  application:
    name: charge
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: systempass
    url: jdbc:mysql://localhost:3306/charge
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/