server:
  port: 19000

spring:
  application:
    name: reservation-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka